import { useState, useEffect, useCallback } from "react";
import { AI_TIMEOUT_MS, get, post } from "../../api/axios";

// ---------------------------------------------------------------------------
// Types — aligned to Java DTOs exactly
// ---------------------------------------------------------------------------

export type ItemType = "READINESS_REPORT" | "MOCK_INTERVIEW" | "PRIORITY_SLOT";
export type TransactionType = "CHALLENGE" | "STORE_PURCHASE";
export type StoreCategory = "REPORT" | "INTERVIEW" | "VISIBILITY";

export interface StoreItemResponse {
  id: number;
  name: string;
  description: string;
  costXp: number;
  itemType: ItemType;
}

export interface UserPurchaseResponse {
  id: number;
  itemId: number;
  itemName: string;
  itemType: ItemType;
  associatedJobId: number | null;
  associatedJobTitle: string | null;
  isUsed: boolean;
  purchasedAt: string;
}

export interface XPTransactionResponse {
  id: number;
  amount: number;
  sourceType: TransactionType;
  referenceId: number | null;
  createdAt: string;
}

// Raw backend DTOs — fields are PLAIN PROSE TEXT from Gemini, NOT JSON
export interface MockInterviewResponse {
  id: number;
  purchaseId: number;
  questionsText: string | null;   // Raw Gemini prose: interview questions
  userAnswersText: string | null; // User's typed answers
  aiFeedbackText: string | null;  // Raw Gemini prose: feedback
  createdAt: string;
}

export interface ReadinessReportResponse {
  id: number;
  purchaseId: number;
  reportContent: string | null; // Raw Gemini prose: the full report
  generatedAt: string;
}

// ---------------------------------------------------------------------------
// UI-enriched store item type
// ---------------------------------------------------------------------------

export interface StoreItemWithMeta extends StoreItemResponse {
  category: StoreCategory;
  icon: string;
  tagline: string;
  features: string[];
  badge?: "POPULAR" | "NEW" | "LIMITED";
}

// ---------------------------------------------------------------------------
// Interview phase
// ---------------------------------------------------------------------------

export type InterviewPhase =
  | "idle"        // purchase exists, interview not started
  | "starting"    // POST /start in flight
  | "answering"   // questions loaded, user typing
  | "submitting"  // POST /submit in flight
  | "completed";  // feedback received — read-only view

// ---------------------------------------------------------------------------
// Item UI metadata (client-side only)
// ---------------------------------------------------------------------------

const ITEM_META: Record<ItemType, Omit<StoreItemWithMeta, keyof StoreItemResponse>> = {
  READINESS_REPORT: {
    category: "REPORT",
    icon: "📊",
    tagline: "Know exactly where you stand.",
    features: [
      "AI-powered career readiness assessment",
      "Skill gap analysis against your verified badges",
      "Personalised recommendations & next steps",
      "Career readiness score out of 100",
      "Strengths & improvement areas",
    ],
    badge: "POPULAR",
  },
  MOCK_INTERVIEW: {
    category: "INTERVIEW",
    icon: "🎙️",
    tagline: "Practice until perfection.",
    features: [
      "Job-specific questions generated by Gemini AI",
      "Answer at your own pace",
      "Detailed AI feedback on all your answers",
      "Technical + behavioural question mix",
      "Sentiment-aware interviewer persona",
    ],
    badge: "NEW",
  },
  PRIORITY_SLOT: {
    category: "VISIBILITY",
    icon: "⭐",
    tagline: "Get seen first.",
    features: [
      "Jump to the top of the applicant queue",
      "High-visibility placement for recruiters",
      "One slot per job application",
      "Slots ranked 1st, 2nd, 3rd priority",
    ],
  },
};

export function enrichItem(item: StoreItemResponse): StoreItemWithMeta {
  return { ...item, ...ITEM_META[item.itemType] };
}

export const PRIORITY_SLOT_RANKS = [
  { rank: 3, label: "3rd Priority", xp: 100, color: "#94A3B8" },
  { rank: 2, label: "2nd Priority", xp: 120, color: "#60A5FA" },
  { rank: 1, label: "1st Priority", xp: 150, color: "#FCD34D" },
];

// ---------------------------------------------------------------------------
// useStore — store items, purchases, XP balance
// ---------------------------------------------------------------------------

export interface UseStoreReturn {
  items: StoreItemWithMeta[];
  purchases: UserPurchaseResponse[];
  unusedPurchases: UserPurchaseResponse[];
  xpBalance: number;
  isLoading: boolean;
  isPurchasing: boolean;
  error: string | null;
  purchaseItem: (
    itemId: number,
    associatedJobId?: number | null,
    slotRank?: number | null
  ) => Promise<{ success: boolean; purchaseId?: number; error?: string }>;
  refetch: () => void;
}

export const useStore = (): UseStoreReturn => {
  const [items, setItems] = useState<StoreItemWithMeta[]>([]);
  const [purchases, setPurchases] = useState<UserPurchaseResponse[]>([]);
  const [unusedPurchases, setUnusedPurchases] = useState<UserPurchaseResponse[]>([]);
  const [xpBalance, setXpBalance] = useState(0);
  const [isLoading, setIsLoading] = useState(true);
  const [isPurchasing, setIsPurchasing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [tick, setTick] = useState(0);

  useEffect(() => {
    let cancelled = false;
    setIsLoading(true);
    setError(null);

    Promise.all([
      get<StoreItemResponse[]>("/user/store/items"),
      get<UserPurchaseResponse[]>("/user/store/purchases"),
      get<UserPurchaseResponse[]>("/user/store/purchases/unused"),
      get<{ xpBalance: number }>("/user/profile"),
    ])
      .then(([rawItems, rawPurchases, rawUnused, profile]) => {
        if (cancelled) return;
        setItems(rawItems.map(enrichItem));
        setPurchases(rawPurchases);
        setUnusedPurchases(rawUnused);
        // Use the authoritative xpBalance from the user profile (single source of truth)
        setXpBalance(profile.xpBalance ?? 0);
      })
      .catch((err) => { if (!cancelled) setError(err.message ?? "Failed to load store."); })
      .finally(() => { if (!cancelled) setIsLoading(false); });

    return () => { cancelled = true; };
  }, [tick]);

  const purchaseItem = useCallback(
    async (itemId: number, associatedJobId?: number | null, slotRank?: number | null) => {
      setIsPurchasing(true);
      try {
        const body: { itemId: number; associatedJobId?: number | null; slotRank?: number } = { itemId };
        if (associatedJobId != null) body.associatedJobId = associatedJobId;
        if (slotRank != null) body.slotRank = slotRank;

        const purchase = await post<UserPurchaseResponse>("/user/store/purchase", body);
        setPurchases((prev) => [purchase, ...prev]);
        if (!purchase.isUsed) setUnusedPurchases((prev) => [purchase, ...prev]);

        // Refetch authoritative balance from profile
        try {
          const profile = await get<{ xpBalance: number }>("/user/profile");
          setXpBalance(profile.xpBalance ?? 0);
        } catch {
          // Fallback: optimistic deduction
          const item = items.find((i) => i.id === itemId);
          if (item) setXpBalance((prev) => Math.max(0, prev - item.costXp));
        }

        return { success: true, purchaseId: purchase.id };
      } catch (err: unknown) {
        return { success: false, error: (err as Error).message ?? "Purchase failed." };
      } finally {
        setIsPurchasing(false);
      }
    },
    [items]
  );

  return {
    items, purchases, unusedPurchases, xpBalance,
    isLoading, isPurchasing, error, purchaseItem,
    refetch: () => setTick((t) => t + 1),
  };
};

// ---------------------------------------------------------------------------
// useReadinessReport
//   GET  /api/user/ai/report/{purchaseId} — retrieve existing report
//   POST /api/user/ai/report/{purchaseId} — generate new report
//   reportContent is RAW GEMINI PROSE — render as plain text / markdown
// ---------------------------------------------------------------------------

export interface UseReadinessReportReturn {
  report: ReadinessReportResponse | null;
  isLoading: boolean;    // initial fetch
  isGenerating: boolean; // POST in flight
  error: string | null;
  generate: () => Promise<void>;
}

export function useReadinessReport(purchaseId: number | null): UseReadinessReportReturn {
  const [report, setReport] = useState<ReadinessReportResponse | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!purchaseId) return;
    setIsLoading(true);
    setError(null);

    get<ReadinessReportResponse>(`/user/ai/report/${purchaseId}`)
      .then((res) => setReport(res))
      .catch(() => setReport(null)) // 404 = not generated yet — show generate button
      .finally(() => setIsLoading(false));
  }, [purchaseId]);

  const generate = useCallback(async () => {
    if (!purchaseId) return;
    setIsGenerating(true);
    setError(null);
    try {
      const res = await post<ReadinessReportResponse>(
        `/user/ai/report/${purchaseId}`,
        {},
        { timeout: AI_TIMEOUT_MS }
      );
      setReport(res);
    } catch (err: unknown) {
      setError((err as Error).message ?? "Failed to generate report.");
    } finally {
      setIsGenerating(false);
    }
  }, [purchaseId]);
 
  return { report, isLoading, isGenerating, error, generate };
}

// ---------------------------------------------------------------------------
// useMockInterview
//   GET  /api/user/ai/interview/{purchaseId}     — load existing session
//   POST /api/user/ai/interview/start/{purchaseId} — generate questions
//   POST /api/user/ai/interview/submit            — submit answers, get feedback
//   questionsText & aiFeedbackText are RAW GEMINI PROSE — render as plain text
// ---------------------------------------------------------------------------

export interface UseMockInterviewReturn {
  interview: MockInterviewResponse | null;
  phase: InterviewPhase;
  answers: string;
  isLoading: boolean;
  error: string | null;
  setAnswers: (v: string) => void;
  startInterview: () => Promise<void>;
  submitAnswers: () => Promise<void>;
}

export function useMockInterview(purchaseId: number | null): UseMockInterviewReturn {
  const [interview, setInterview] = useState<MockInterviewResponse | null>(null);
  const [phase, setPhase] = useState<InterviewPhase>("idle");
  const [answers, setAnswers] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!purchaseId) return;
    setIsLoading(true);
    setError(null);

    get<MockInterviewResponse>(`/user/ai/interview/${purchaseId}`)
      .then((res) => {
        setInterview(res);
        if (res.aiFeedbackText) {
          setPhase("completed");
          setAnswers(res.userAnswersText ?? "");
        } else if (res.questionsText) {
          setPhase("answering");
        } else {
          setPhase("idle");
        }
      })
      .catch(() => setPhase("idle")) // not started yet
      .finally(() => setIsLoading(false));
  }, [purchaseId]);

   const startInterview = useCallback(async () => {
    if (!purchaseId) return;
    setPhase("starting");
    setError(null);
    try {
      const res = await post<MockInterviewResponse>(
        `/user/ai/interview/start/${purchaseId}`,
        {},
        { timeout: AI_TIMEOUT_MS }
      );
      setInterview(res);
      setPhase("answering");
    } catch (err: unknown) {
      setError((err as Error).message ?? "Failed to start interview.");
      setPhase("idle");
    }
  }, [purchaseId]);
 
  const submitAnswers = useCallback(async () => {
    if (!purchaseId || !answers.trim()) return;
    setPhase("submitting");
    setError(null);
    try {
      const res = await post<MockInterviewResponse>(
        "/user/ai/interview/submit",
        { purchaseId, userAnswersText: answers },
        { timeout: AI_TIMEOUT_MS }
      );
      setInterview(res);
      setPhase("completed");
    } catch (err: unknown) {
      setError((err as Error).message ?? "Failed to submit answers.");
      setPhase("answering");
    }
  }, [purchaseId, answers]);

  return { interview, phase, answers, isLoading, error, setAnswers, startInterview, submitAnswers };
}